// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.35.2
// 	protoc        v5.27.1
// source: third.proto

package third

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	anypb "google.golang.org/protobuf/types/known/anypb"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type UpdateFcmTokenReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	FcmToken   string `protobuf:"bytes,1,opt,name=fcmToken,proto3" json:"fcmToken"`
	ExpireTime int64  `protobuf:"varint,2,opt,name=expireTime,proto3" json:"expireTime"`
}

func (x *UpdateFcmTokenReq) Reset() {
	*x = UpdateFcmTokenReq{}
	mi := &file_third_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateFcmTokenReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateFcmTokenReq) ProtoMessage() {}

func (x *UpdateFcmTokenReq) ProtoReflect() protoreflect.Message {
	mi := &file_third_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateFcmTokenReq.ProtoReflect.Descriptor instead.
func (*UpdateFcmTokenReq) Descriptor() ([]byte, []int) {
	return file_third_proto_rawDescGZIP(), []int{0}
}

func (x *UpdateFcmTokenReq) GetFcmToken() string {
	if x != nil {
		return x.FcmToken
	}
	return ""
}

func (x *UpdateFcmTokenReq) GetExpireTime() int64 {
	if x != nil {
		return x.ExpireTime
	}
	return 0
}

type UpdateFcmTokenResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *UpdateFcmTokenResp) Reset() {
	*x = UpdateFcmTokenResp{}
	mi := &file_third_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateFcmTokenResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateFcmTokenResp) ProtoMessage() {}

func (x *UpdateFcmTokenResp) ProtoReflect() protoreflect.Message {
	mi := &file_third_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateFcmTokenResp.ProtoReflect.Descriptor instead.
func (*UpdateFcmTokenResp) Descriptor() ([]byte, []int) {
	return file_third_proto_rawDescGZIP(), []int{1}
}

type SetAppBadgeReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	AppUnreadCount int32 `protobuf:"varint,1,opt,name=appUnreadCount,proto3" json:"appUnreadCount"`
}

func (x *SetAppBadgeReq) Reset() {
	*x = SetAppBadgeReq{}
	mi := &file_third_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetAppBadgeReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetAppBadgeReq) ProtoMessage() {}

func (x *SetAppBadgeReq) ProtoReflect() protoreflect.Message {
	mi := &file_third_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetAppBadgeReq.ProtoReflect.Descriptor instead.
func (*SetAppBadgeReq) Descriptor() ([]byte, []int) {
	return file_third_proto_rawDescGZIP(), []int{2}
}

func (x *SetAppBadgeReq) GetAppUnreadCount() int32 {
	if x != nil {
		return x.AppUnreadCount
	}
	return 0
}

type SetAppBadgeResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *SetAppBadgeResp) Reset() {
	*x = SetAppBadgeResp{}
	mi := &file_third_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetAppBadgeResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetAppBadgeResp) ProtoMessage() {}

func (x *SetAppBadgeResp) ProtoReflect() protoreflect.Message {
	mi := &file_third_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetAppBadgeResp.ProtoReflect.Descriptor instead.
func (*SetAppBadgeResp) Descriptor() ([]byte, []int) {
	return file_third_proto_rawDescGZIP(), []int{3}
}

type UploadLogsReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Line int32  `protobuf:"varint,1,opt,name=line,proto3" json:"line"`
	Ex   string `protobuf:"bytes,2,opt,name=ex,proto3" json:"ex"`
}

func (x *UploadLogsReq) Reset() {
	*x = UploadLogsReq{}
	mi := &file_third_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UploadLogsReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UploadLogsReq) ProtoMessage() {}

func (x *UploadLogsReq) ProtoReflect() protoreflect.Message {
	mi := &file_third_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UploadLogsReq.ProtoReflect.Descriptor instead.
func (*UploadLogsReq) Descriptor() ([]byte, []int) {
	return file_third_proto_rawDescGZIP(), []int{4}
}

func (x *UploadLogsReq) GetLine() int32 {
	if x != nil {
		return x.Line
	}
	return 0
}

func (x *UploadLogsReq) GetEx() string {
	if x != nil {
		return x.Ex
	}
	return ""
}

type UploadLogsResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *UploadLogsResp) Reset() {
	*x = UploadLogsResp{}
	mi := &file_third_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UploadLogsResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UploadLogsResp) ProtoMessage() {}

func (x *UploadLogsResp) ProtoReflect() protoreflect.Message {
	mi := &file_third_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UploadLogsResp.ProtoReflect.Descriptor instead.
func (*UploadLogsResp) Descriptor() ([]byte, []int) {
	return file_third_proto_rawDescGZIP(), []int{5}
}

type LogKv struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Key   string     `protobuf:"bytes,1,opt,name=key,proto3" json:"key"`
	Value *anypb.Any `protobuf:"bytes,2,opt,name=value,proto3" json:"value"`
}

func (x *LogKv) Reset() {
	*x = LogKv{}
	mi := &file_third_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LogKv) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LogKv) ProtoMessage() {}

func (x *LogKv) ProtoReflect() protoreflect.Message {
	mi := &file_third_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LogKv.ProtoReflect.Descriptor instead.
func (*LogKv) Descriptor() ([]byte, []int) {
	return file_third_proto_rawDescGZIP(), []int{6}
}

func (x *LogKv) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *LogKv) GetValue() *anypb.Any {
	if x != nil {
		return x.Value
	}
	return nil
}

type LogReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	LogLevel int32    `protobuf:"varint,1,opt,name=logLevel,proto3" json:"logLevel"`
	File     string   `protobuf:"bytes,2,opt,name=file,proto3" json:"file"`
	Line     int32    `protobuf:"varint,3,opt,name=line,proto3" json:"line"`
	Msg      string   `protobuf:"bytes,4,opt,name=msg,proto3" json:"msg"`
	Err      string   `protobuf:"bytes,5,opt,name=err,proto3" json:"err"`
	Kvs      []*LogKv `protobuf:"bytes,6,rep,name=kvs,proto3" json:"kvs"`
}

func (x *LogReq) Reset() {
	*x = LogReq{}
	mi := &file_third_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LogReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LogReq) ProtoMessage() {}

func (x *LogReq) ProtoReflect() protoreflect.Message {
	mi := &file_third_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LogReq.ProtoReflect.Descriptor instead.
func (*LogReq) Descriptor() ([]byte, []int) {
	return file_third_proto_rawDescGZIP(), []int{7}
}

func (x *LogReq) GetLogLevel() int32 {
	if x != nil {
		return x.LogLevel
	}
	return 0
}

func (x *LogReq) GetFile() string {
	if x != nil {
		return x.File
	}
	return ""
}

func (x *LogReq) GetLine() int32 {
	if x != nil {
		return x.Line
	}
	return 0
}

func (x *LogReq) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

func (x *LogReq) GetErr() string {
	if x != nil {
		return x.Err
	}
	return ""
}

func (x *LogReq) GetKvs() []*LogKv {
	if x != nil {
		return x.Kvs
	}
	return nil
}

type LogResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *LogResp) Reset() {
	*x = LogResp{}
	mi := &file_third_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LogResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LogResp) ProtoMessage() {}

func (x *LogResp) ProtoReflect() protoreflect.Message {
	mi := &file_third_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LogResp.ProtoReflect.Descriptor instead.
func (*LogResp) Descriptor() ([]byte, []int) {
	return file_third_proto_rawDescGZIP(), []int{8}
}

var File_third_proto protoreflect.FileDescriptor

var file_third_proto_rawDesc = []byte{
	0x0a, 0x0b, 0x74, 0x68, 0x69, 0x72, 0x64, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x10, 0x6f,
	0x70, 0x65, 0x6e, 0x69, 0x6d, 0x2e, 0x73, 0x64, 0x6b, 0x2e, 0x74, 0x68, 0x69, 0x72, 0x64, 0x1a,
	0x10, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x61, 0x6e, 0x79, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x22, 0x4f, 0x0a, 0x11, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x46, 0x63, 0x6d, 0x54, 0x6f,
	0x6b, 0x65, 0x6e, 0x52, 0x65, 0x71, 0x12, 0x1a, 0x0a, 0x08, 0x66, 0x63, 0x6d, 0x54, 0x6f, 0x6b,
	0x65, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x66, 0x63, 0x6d, 0x54, 0x6f, 0x6b,
	0x65, 0x6e, 0x12, 0x1e, 0x0a, 0x0a, 0x65, 0x78, 0x70, 0x69, 0x72, 0x65, 0x54, 0x69, 0x6d, 0x65,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x0a, 0x65, 0x78, 0x70, 0x69, 0x72, 0x65, 0x54, 0x69,
	0x6d, 0x65, 0x22, 0x14, 0x0a, 0x12, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x46, 0x63, 0x6d, 0x54,
	0x6f, 0x6b, 0x65, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x22, 0x38, 0x0a, 0x0e, 0x53, 0x65, 0x74, 0x41,
	0x70, 0x70, 0x42, 0x61, 0x64, 0x67, 0x65, 0x52, 0x65, 0x71, 0x12, 0x26, 0x0a, 0x0e, 0x61, 0x70,
	0x70, 0x55, 0x6e, 0x72, 0x65, 0x61, 0x64, 0x43, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x05, 0x52, 0x0e, 0x61, 0x70, 0x70, 0x55, 0x6e, 0x72, 0x65, 0x61, 0x64, 0x43, 0x6f, 0x75,
	0x6e, 0x74, 0x22, 0x11, 0x0a, 0x0f, 0x53, 0x65, 0x74, 0x41, 0x70, 0x70, 0x42, 0x61, 0x64, 0x67,
	0x65, 0x52, 0x65, 0x73, 0x70, 0x22, 0x33, 0x0a, 0x0d, 0x55, 0x70, 0x6c, 0x6f, 0x61, 0x64, 0x4c,
	0x6f, 0x67, 0x73, 0x52, 0x65, 0x71, 0x12, 0x12, 0x0a, 0x04, 0x6c, 0x69, 0x6e, 0x65, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x05, 0x52, 0x04, 0x6c, 0x69, 0x6e, 0x65, 0x12, 0x0e, 0x0a, 0x02, 0x65, 0x78,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x65, 0x78, 0x22, 0x10, 0x0a, 0x0e, 0x55, 0x70,
	0x6c, 0x6f, 0x61, 0x64, 0x4c, 0x6f, 0x67, 0x73, 0x52, 0x65, 0x73, 0x70, 0x22, 0x45, 0x0a, 0x05,
	0x4c, 0x6f, 0x67, 0x4b, 0x76, 0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x03, 0x6b, 0x65, 0x79, 0x12, 0x2a, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x14, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x41, 0x6e, 0x79, 0x52, 0x05, 0x76, 0x61,
	0x6c, 0x75, 0x65, 0x22, 0x9b, 0x01, 0x0a, 0x06, 0x4c, 0x6f, 0x67, 0x52, 0x65, 0x71, 0x12, 0x1a,
	0x0a, 0x08, 0x6c, 0x6f, 0x67, 0x4c, 0x65, 0x76, 0x65, 0x6c, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05,
	0x52, 0x08, 0x6c, 0x6f, 0x67, 0x4c, 0x65, 0x76, 0x65, 0x6c, 0x12, 0x12, 0x0a, 0x04, 0x66, 0x69,
	0x6c, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x66, 0x69, 0x6c, 0x65, 0x12, 0x12,
	0x0a, 0x04, 0x6c, 0x69, 0x6e, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x52, 0x04, 0x6c, 0x69,
	0x6e, 0x65, 0x12, 0x10, 0x0a, 0x03, 0x6d, 0x73, 0x67, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x03, 0x6d, 0x73, 0x67, 0x12, 0x10, 0x0a, 0x03, 0x65, 0x72, 0x72, 0x18, 0x05, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x03, 0x65, 0x72, 0x72, 0x12, 0x29, 0x0a, 0x03, 0x6b, 0x76, 0x73, 0x18, 0x06, 0x20,
	0x03, 0x28, 0x0b, 0x32, 0x17, 0x2e, 0x6f, 0x70, 0x65, 0x6e, 0x69, 0x6d, 0x2e, 0x73, 0x64, 0x6b,
	0x2e, 0x74, 0x68, 0x69, 0x72, 0x64, 0x2e, 0x4c, 0x6f, 0x67, 0x4b, 0x76, 0x52, 0x03, 0x6b, 0x76,
	0x73, 0x22, 0x09, 0x0a, 0x07, 0x4c, 0x6f, 0x67, 0x52, 0x65, 0x73, 0x70, 0x42, 0x38, 0x5a, 0x36,
	0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x6f, 0x70, 0x65, 0x6e, 0x69,
	0x6d, 0x73, 0x64, 0x6b, 0x2f, 0x6f, 0x70, 0x65, 0x6e, 0x69, 0x6d, 0x2d, 0x73, 0x64, 0x6b, 0x2d,
	0x63, 0x6f, 0x72, 0x65, 0x2f, 0x76, 0x33, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x67, 0x6f,
	0x2f, 0x74, 0x68, 0x69, 0x72, 0x64, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_third_proto_rawDescOnce sync.Once
	file_third_proto_rawDescData = file_third_proto_rawDesc
)

func file_third_proto_rawDescGZIP() []byte {
	file_third_proto_rawDescOnce.Do(func() {
		file_third_proto_rawDescData = protoimpl.X.CompressGZIP(file_third_proto_rawDescData)
	})
	return file_third_proto_rawDescData
}

var file_third_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_third_proto_goTypes = []any{
	(*UpdateFcmTokenReq)(nil),  // 0: openim.sdk.third.UpdateFcmTokenReq
	(*UpdateFcmTokenResp)(nil), // 1: openim.sdk.third.UpdateFcmTokenResp
	(*SetAppBadgeReq)(nil),     // 2: openim.sdk.third.SetAppBadgeReq
	(*SetAppBadgeResp)(nil),    // 3: openim.sdk.third.SetAppBadgeResp
	(*UploadLogsReq)(nil),      // 4: openim.sdk.third.UploadLogsReq
	(*UploadLogsResp)(nil),     // 5: openim.sdk.third.UploadLogsResp
	(*LogKv)(nil),              // 6: openim.sdk.third.LogKv
	(*LogReq)(nil),             // 7: openim.sdk.third.LogReq
	(*LogResp)(nil),            // 8: openim.sdk.third.LogResp
	(*anypb.Any)(nil),          // 9: google.protobuf.Any
}
var file_third_proto_depIdxs = []int32{
	9, // 0: openim.sdk.third.LogKv.value:type_name -> google.protobuf.Any
	6, // 1: openim.sdk.third.LogReq.kvs:type_name -> openim.sdk.third.LogKv
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_third_proto_init() }
func file_third_proto_init() {
	if File_third_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_third_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_third_proto_goTypes,
		DependencyIndexes: file_third_proto_depIdxs,
		MessageInfos:      file_third_proto_msgTypes,
	}.Build()
	File_third_proto = out.File
	file_third_proto_rawDesc = nil
	file_third_proto_goTypes = nil
	file_third_proto_depIdxs = nil
}
