// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.35.2
// 	protoc        v5.27.1
// source: js-bridge.proto

package js_bridge

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type JsFileOpenReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Uuid string `protobuf:"bytes,1,opt,name=uuid,proto3" json:"uuid"`
}

func (x *JsFileOpenReq) Reset() {
	*x = JsFileOpenReq{}
	mi := &file_js_bridge_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *JsFileOpenReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JsFileOpenReq) ProtoMessage() {}

func (x *JsFileOpenReq) ProtoReflect() protoreflect.Message {
	mi := &file_js_bridge_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JsFileOpenReq.ProtoReflect.Descriptor instead.
func (*JsFileOpenReq) Descriptor() ([]byte, []int) {
	return file_js_bridge_proto_rawDescGZIP(), []int{0}
}

func (x *JsFileOpenReq) GetUuid() string {
	if x != nil {
		return x.Uuid
	}
	return ""
}

type JsFileOpenResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Size int64 `protobuf:"varint,1,opt,name=size,proto3" json:"size"`
}

func (x *JsFileOpenResp) Reset() {
	*x = JsFileOpenResp{}
	mi := &file_js_bridge_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *JsFileOpenResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JsFileOpenResp) ProtoMessage() {}

func (x *JsFileOpenResp) ProtoReflect() protoreflect.Message {
	mi := &file_js_bridge_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JsFileOpenResp.ProtoReflect.Descriptor instead.
func (*JsFileOpenResp) Descriptor() ([]byte, []int) {
	return file_js_bridge_proto_rawDescGZIP(), []int{1}
}

func (x *JsFileOpenResp) GetSize() int64 {
	if x != nil {
		return x.Size
	}
	return 0
}

type JsFileReadReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Uuid   string `protobuf:"bytes,1,opt,name=uuid,proto3" json:"uuid"`
	Offset int64  `protobuf:"varint,2,opt,name=offset,proto3" json:"offset"`
	Length int64  `protobuf:"varint,3,opt,name=length,proto3" json:"length"`
}

func (x *JsFileReadReq) Reset() {
	*x = JsFileReadReq{}
	mi := &file_js_bridge_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *JsFileReadReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JsFileReadReq) ProtoMessage() {}

func (x *JsFileReadReq) ProtoReflect() protoreflect.Message {
	mi := &file_js_bridge_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JsFileReadReq.ProtoReflect.Descriptor instead.
func (*JsFileReadReq) Descriptor() ([]byte, []int) {
	return file_js_bridge_proto_rawDescGZIP(), []int{2}
}

func (x *JsFileReadReq) GetUuid() string {
	if x != nil {
		return x.Uuid
	}
	return ""
}

func (x *JsFileReadReq) GetOffset() int64 {
	if x != nil {
		return x.Offset
	}
	return 0
}

func (x *JsFileReadReq) GetLength() int64 {
	if x != nil {
		return x.Length
	}
	return 0
}

type JsFileReadResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Data []byte `protobuf:"bytes,1,opt,name=data,proto3" json:"data"`
}

func (x *JsFileReadResp) Reset() {
	*x = JsFileReadResp{}
	mi := &file_js_bridge_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *JsFileReadResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JsFileReadResp) ProtoMessage() {}

func (x *JsFileReadResp) ProtoReflect() protoreflect.Message {
	mi := &file_js_bridge_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JsFileReadResp.ProtoReflect.Descriptor instead.
func (*JsFileReadResp) Descriptor() ([]byte, []int) {
	return file_js_bridge_proto_rawDescGZIP(), []int{3}
}

func (x *JsFileReadResp) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

type JsFileCloseReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Uuid string `protobuf:"bytes,1,opt,name=uuid,proto3" json:"uuid"`
}

func (x *JsFileCloseReq) Reset() {
	*x = JsFileCloseReq{}
	mi := &file_js_bridge_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *JsFileCloseReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JsFileCloseReq) ProtoMessage() {}

func (x *JsFileCloseReq) ProtoReflect() protoreflect.Message {
	mi := &file_js_bridge_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JsFileCloseReq.ProtoReflect.Descriptor instead.
func (*JsFileCloseReq) Descriptor() ([]byte, []int) {
	return file_js_bridge_proto_rawDescGZIP(), []int{4}
}

func (x *JsFileCloseReq) GetUuid() string {
	if x != nil {
		return x.Uuid
	}
	return ""
}

type JsFileCloseResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *JsFileCloseResp) Reset() {
	*x = JsFileCloseResp{}
	mi := &file_js_bridge_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *JsFileCloseResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JsFileCloseResp) ProtoMessage() {}

func (x *JsFileCloseResp) ProtoReflect() protoreflect.Message {
	mi := &file_js_bridge_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JsFileCloseResp.ProtoReflect.Descriptor instead.
func (*JsFileCloseResp) Descriptor() ([]byte, []int) {
	return file_js_bridge_proto_rawDescGZIP(), []int{5}
}

type JsSqliteOpenReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name"`
}

func (x *JsSqliteOpenReq) Reset() {
	*x = JsSqliteOpenReq{}
	mi := &file_js_bridge_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *JsSqliteOpenReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JsSqliteOpenReq) ProtoMessage() {}

func (x *JsSqliteOpenReq) ProtoReflect() protoreflect.Message {
	mi := &file_js_bridge_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JsSqliteOpenReq.ProtoReflect.Descriptor instead.
func (*JsSqliteOpenReq) Descriptor() ([]byte, []int) {
	return file_js_bridge_proto_rawDescGZIP(), []int{6}
}

func (x *JsSqliteOpenReq) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type JsSqliteOpenResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id int64 `protobuf:"varint,1,opt,name=id,proto3" json:"id"`
}

func (x *JsSqliteOpenResp) Reset() {
	*x = JsSqliteOpenResp{}
	mi := &file_js_bridge_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *JsSqliteOpenResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JsSqliteOpenResp) ProtoMessage() {}

func (x *JsSqliteOpenResp) ProtoReflect() protoreflect.Message {
	mi := &file_js_bridge_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JsSqliteOpenResp.ProtoReflect.Descriptor instead.
func (*JsSqliteOpenResp) Descriptor() ([]byte, []int) {
	return file_js_bridge_proto_rawDescGZIP(), []int{7}
}

func (x *JsSqliteOpenResp) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type JsSqliteCloseReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id int64 `protobuf:"varint,1,opt,name=id,proto3" json:"id"`
}

func (x *JsSqliteCloseReq) Reset() {
	*x = JsSqliteCloseReq{}
	mi := &file_js_bridge_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *JsSqliteCloseReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JsSqliteCloseReq) ProtoMessage() {}

func (x *JsSqliteCloseReq) ProtoReflect() protoreflect.Message {
	mi := &file_js_bridge_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JsSqliteCloseReq.ProtoReflect.Descriptor instead.
func (*JsSqliteCloseReq) Descriptor() ([]byte, []int) {
	return file_js_bridge_proto_rawDescGZIP(), []int{8}
}

func (x *JsSqliteCloseReq) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type JsSqliteCloseResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *JsSqliteCloseResp) Reset() {
	*x = JsSqliteCloseResp{}
	mi := &file_js_bridge_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *JsSqliteCloseResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JsSqliteCloseResp) ProtoMessage() {}

func (x *JsSqliteCloseResp) ProtoReflect() protoreflect.Message {
	mi := &file_js_bridge_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JsSqliteCloseResp.ProtoReflect.Descriptor instead.
func (*JsSqliteCloseResp) Descriptor() ([]byte, []int) {
	return file_js_bridge_proto_rawDescGZIP(), []int{9}
}

type JsSqliteExecReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id   int64  `protobuf:"varint,1,opt,name=id,proto3" json:"id"`
	Sql  string `protobuf:"bytes,2,opt,name=sql,proto3" json:"sql"`
	Args string `protobuf:"bytes,3,opt,name=args,proto3" json:"args"` // json array
}

func (x *JsSqliteExecReq) Reset() {
	*x = JsSqliteExecReq{}
	mi := &file_js_bridge_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *JsSqliteExecReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JsSqliteExecReq) ProtoMessage() {}

func (x *JsSqliteExecReq) ProtoReflect() protoreflect.Message {
	mi := &file_js_bridge_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JsSqliteExecReq.ProtoReflect.Descriptor instead.
func (*JsSqliteExecReq) Descriptor() ([]byte, []int) {
	return file_js_bridge_proto_rawDescGZIP(), []int{10}
}

func (x *JsSqliteExecReq) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *JsSqliteExecReq) GetSql() string {
	if x != nil {
		return x.Sql
	}
	return ""
}

func (x *JsSqliteExecReq) GetArgs() string {
	if x != nil {
		return x.Args
	}
	return ""
}

type JsSqliteExecResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Affected int64 `protobuf:"varint,1,opt,name=affected,proto3" json:"affected"`
}

func (x *JsSqliteExecResp) Reset() {
	*x = JsSqliteExecResp{}
	mi := &file_js_bridge_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *JsSqliteExecResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JsSqliteExecResp) ProtoMessage() {}

func (x *JsSqliteExecResp) ProtoReflect() protoreflect.Message {
	mi := &file_js_bridge_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JsSqliteExecResp.ProtoReflect.Descriptor instead.
func (*JsSqliteExecResp) Descriptor() ([]byte, []int) {
	return file_js_bridge_proto_rawDescGZIP(), []int{11}
}

func (x *JsSqliteExecResp) GetAffected() int64 {
	if x != nil {
		return x.Affected
	}
	return 0
}

type JsSqliteQueryReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id   int64  `protobuf:"varint,1,opt,name=id,proto3" json:"id"`
	Sql  string `protobuf:"bytes,2,opt,name=sql,proto3" json:"sql"`
	Args string `protobuf:"bytes,3,opt,name=args,proto3" json:"args"` // json array
}

func (x *JsSqliteQueryReq) Reset() {
	*x = JsSqliteQueryReq{}
	mi := &file_js_bridge_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *JsSqliteQueryReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JsSqliteQueryReq) ProtoMessage() {}

func (x *JsSqliteQueryReq) ProtoReflect() protoreflect.Message {
	mi := &file_js_bridge_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JsSqliteQueryReq.ProtoReflect.Descriptor instead.
func (*JsSqliteQueryReq) Descriptor() ([]byte, []int) {
	return file_js_bridge_proto_rawDescGZIP(), []int{12}
}

func (x *JsSqliteQueryReq) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *JsSqliteQueryReq) GetSql() string {
	if x != nil {
		return x.Sql
	}
	return ""
}

func (x *JsSqliteQueryReq) GetArgs() string {
	if x != nil {
		return x.Args
	}
	return ""
}

type JsSqliteQueryResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Result string `protobuf:"bytes,1,opt,name=result,proto3" json:"result"` // json array
}

func (x *JsSqliteQueryResp) Reset() {
	*x = JsSqliteQueryResp{}
	mi := &file_js_bridge_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *JsSqliteQueryResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JsSqliteQueryResp) ProtoMessage() {}

func (x *JsSqliteQueryResp) ProtoReflect() protoreflect.Message {
	mi := &file_js_bridge_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JsSqliteQueryResp.ProtoReflect.Descriptor instead.
func (*JsSqliteQueryResp) Descriptor() ([]byte, []int) {
	return file_js_bridge_proto_rawDescGZIP(), []int{13}
}

func (x *JsSqliteQueryResp) GetResult() string {
	if x != nil {
		return x.Result
	}
	return ""
}

var File_js_bridge_proto protoreflect.FileDescriptor

var file_js_bridge_proto_rawDesc = []byte{
	0x0a, 0x0f, 0x6a, 0x73, 0x2d, 0x62, 0x72, 0x69, 0x64, 0x67, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x12, 0x09, 0x6f, 0x70, 0x65, 0x6e, 0x69, 0x6d, 0x2e, 0x6a, 0x73, 0x22, 0x23, 0x0a, 0x0d,
	0x6a, 0x73, 0x46, 0x69, 0x6c, 0x65, 0x4f, 0x70, 0x65, 0x6e, 0x52, 0x65, 0x71, 0x12, 0x12, 0x0a,
	0x04, 0x75, 0x75, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x75, 0x75, 0x69,
	0x64, 0x22, 0x24, 0x0a, 0x0e, 0x6a, 0x73, 0x46, 0x69, 0x6c, 0x65, 0x4f, 0x70, 0x65, 0x6e, 0x52,
	0x65, 0x73, 0x70, 0x12, 0x12, 0x0a, 0x04, 0x73, 0x69, 0x7a, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x03, 0x52, 0x04, 0x73, 0x69, 0x7a, 0x65, 0x22, 0x53, 0x0a, 0x0d, 0x6a, 0x73, 0x46, 0x69, 0x6c,
	0x65, 0x52, 0x65, 0x61, 0x64, 0x52, 0x65, 0x71, 0x12, 0x12, 0x0a, 0x04, 0x75, 0x75, 0x69, 0x64,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x75, 0x75, 0x69, 0x64, 0x12, 0x16, 0x0a, 0x06,
	0x6f, 0x66, 0x66, 0x73, 0x65, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x06, 0x6f, 0x66,
	0x66, 0x73, 0x65, 0x74, 0x12, 0x16, 0x0a, 0x06, 0x6c, 0x65, 0x6e, 0x67, 0x74, 0x68, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x03, 0x52, 0x06, 0x6c, 0x65, 0x6e, 0x67, 0x74, 0x68, 0x22, 0x24, 0x0a, 0x0e,
	0x6a, 0x73, 0x46, 0x69, 0x6c, 0x65, 0x52, 0x65, 0x61, 0x64, 0x52, 0x65, 0x73, 0x70, 0x12, 0x12,
	0x0a, 0x04, 0x64, 0x61, 0x74, 0x61, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x04, 0x64, 0x61,
	0x74, 0x61, 0x22, 0x24, 0x0a, 0x0e, 0x6a, 0x73, 0x46, 0x69, 0x6c, 0x65, 0x43, 0x6c, 0x6f, 0x73,
	0x65, 0x52, 0x65, 0x71, 0x12, 0x12, 0x0a, 0x04, 0x75, 0x75, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x04, 0x75, 0x75, 0x69, 0x64, 0x22, 0x11, 0x0a, 0x0f, 0x6a, 0x73, 0x46, 0x69,
	0x6c, 0x65, 0x43, 0x6c, 0x6f, 0x73, 0x65, 0x52, 0x65, 0x73, 0x70, 0x22, 0x25, 0x0a, 0x0f, 0x6a,
	0x73, 0x53, 0x71, 0x6c, 0x69, 0x74, 0x65, 0x4f, 0x70, 0x65, 0x6e, 0x52, 0x65, 0x71, 0x12, 0x12,
	0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61,
	0x6d, 0x65, 0x22, 0x22, 0x0a, 0x10, 0x6a, 0x73, 0x53, 0x71, 0x6c, 0x69, 0x74, 0x65, 0x4f, 0x70,
	0x65, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x03, 0x52, 0x02, 0x69, 0x64, 0x22, 0x22, 0x0a, 0x10, 0x6a, 0x73, 0x53, 0x71, 0x6c, 0x69,
	0x74, 0x65, 0x43, 0x6c, 0x6f, 0x73, 0x65, 0x52, 0x65, 0x71, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x02, 0x69, 0x64, 0x22, 0x13, 0x0a, 0x11, 0x6a, 0x73,
	0x53, 0x71, 0x6c, 0x69, 0x74, 0x65, 0x43, 0x6c, 0x6f, 0x73, 0x65, 0x52, 0x65, 0x73, 0x70, 0x22,
	0x47, 0x0a, 0x0f, 0x6a, 0x73, 0x53, 0x71, 0x6c, 0x69, 0x74, 0x65, 0x45, 0x78, 0x65, 0x63, 0x52,
	0x65, 0x71, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x02,
	0x69, 0x64, 0x12, 0x10, 0x0a, 0x03, 0x73, 0x71, 0x6c, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x03, 0x73, 0x71, 0x6c, 0x12, 0x12, 0x0a, 0x04, 0x61, 0x72, 0x67, 0x73, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x04, 0x61, 0x72, 0x67, 0x73, 0x22, 0x2e, 0x0a, 0x10, 0x6a, 0x73, 0x53, 0x71,
	0x6c, 0x69, 0x74, 0x65, 0x45, 0x78, 0x65, 0x63, 0x52, 0x65, 0x73, 0x70, 0x12, 0x1a, 0x0a, 0x08,
	0x61, 0x66, 0x66, 0x65, 0x63, 0x74, 0x65, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x08,
	0x61, 0x66, 0x66, 0x65, 0x63, 0x74, 0x65, 0x64, 0x22, 0x48, 0x0a, 0x10, 0x6a, 0x73, 0x53, 0x71,
	0x6c, 0x69, 0x74, 0x65, 0x51, 0x75, 0x65, 0x72, 0x79, 0x52, 0x65, 0x71, 0x12, 0x0e, 0x0a, 0x02,
	0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x02, 0x69, 0x64, 0x12, 0x10, 0x0a, 0x03,
	0x73, 0x71, 0x6c, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x73, 0x71, 0x6c, 0x12, 0x12,
	0x0a, 0x04, 0x61, 0x72, 0x67, 0x73, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x61, 0x72,
	0x67, 0x73, 0x22, 0x2b, 0x0a, 0x11, 0x6a, 0x73, 0x53, 0x71, 0x6c, 0x69, 0x74, 0x65, 0x51, 0x75,
	0x65, 0x72, 0x79, 0x52, 0x65, 0x73, 0x70, 0x12, 0x16, 0x0a, 0x06, 0x72, 0x65, 0x73, 0x75, 0x6c,
	0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x42,
	0x3c, 0x5a, 0x3a, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x6f, 0x70,
	0x65, 0x6e, 0x69, 0x6d, 0x73, 0x64, 0x6b, 0x2f, 0x6f, 0x70, 0x65, 0x6e, 0x69, 0x6d, 0x2d, 0x73,
	0x64, 0x6b, 0x2d, 0x63, 0x6f, 0x72, 0x65, 0x2f, 0x76, 0x33, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x2f, 0x67, 0x6f, 0x2f, 0x6a, 0x73, 0x2d, 0x62, 0x72, 0x69, 0x64, 0x67, 0x65, 0x62, 0x06, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_js_bridge_proto_rawDescOnce sync.Once
	file_js_bridge_proto_rawDescData = file_js_bridge_proto_rawDesc
)

func file_js_bridge_proto_rawDescGZIP() []byte {
	file_js_bridge_proto_rawDescOnce.Do(func() {
		file_js_bridge_proto_rawDescData = protoimpl.X.CompressGZIP(file_js_bridge_proto_rawDescData)
	})
	return file_js_bridge_proto_rawDescData
}

var file_js_bridge_proto_msgTypes = make([]protoimpl.MessageInfo, 14)
var file_js_bridge_proto_goTypes = []any{
	(*JsFileOpenReq)(nil),     // 0: openim.js.jsFileOpenReq
	(*JsFileOpenResp)(nil),    // 1: openim.js.jsFileOpenResp
	(*JsFileReadReq)(nil),     // 2: openim.js.jsFileReadReq
	(*JsFileReadResp)(nil),    // 3: openim.js.jsFileReadResp
	(*JsFileCloseReq)(nil),    // 4: openim.js.jsFileCloseReq
	(*JsFileCloseResp)(nil),   // 5: openim.js.jsFileCloseResp
	(*JsSqliteOpenReq)(nil),   // 6: openim.js.jsSqliteOpenReq
	(*JsSqliteOpenResp)(nil),  // 7: openim.js.jsSqliteOpenResp
	(*JsSqliteCloseReq)(nil),  // 8: openim.js.jsSqliteCloseReq
	(*JsSqliteCloseResp)(nil), // 9: openim.js.jsSqliteCloseResp
	(*JsSqliteExecReq)(nil),   // 10: openim.js.jsSqliteExecReq
	(*JsSqliteExecResp)(nil),  // 11: openim.js.jsSqliteExecResp
	(*JsSqliteQueryReq)(nil),  // 12: openim.js.jsSqliteQueryReq
	(*JsSqliteQueryResp)(nil), // 13: openim.js.jsSqliteQueryResp
}
var file_js_bridge_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_js_bridge_proto_init() }
func file_js_bridge_proto_init() {
	if File_js_bridge_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_js_bridge_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   14,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_js_bridge_proto_goTypes,
		DependencyIndexes: file_js_bridge_proto_depIdxs,
		MessageInfos:      file_js_bridge_proto_msgTypes,
	}.Build()
	File_js_bridge_proto = out.File
	file_js_bridge_proto_rawDesc = nil
	file_js_bridge_proto_goTypes = nil
	file_js_bridge_proto_depIdxs = nil
}
