// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.33.0
// 	protoc        v5.26.0
// source: js_bridge.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type WasmOpenFileReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	SqlString string `protobuf:"bytes,1,opt,name=sqlString,proto3" json:"sqlString,omitempty"`
}

func (x *WasmOpenFileReq) Reset() {
	*x = WasmOpenFileReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_js_bridge_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *WasmOpenFileReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WasmOpenFileReq) ProtoMessage() {}

func (x *WasmOpenFileReq) ProtoReflect() protoreflect.Message {
	mi := &file_js_bridge_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WasmOpenFileReq.ProtoReflect.Descriptor instead.
func (*WasmOpenFileReq) Descriptor() ([]byte, []int) {
	return file_js_bridge_proto_rawDescGZIP(), []int{0}
}

func (x *WasmOpenFileReq) GetSqlString() string {
	if x != nil {
		return x.SqlString
	}
	return ""
}

type WasmOpenFileResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *WasmOpenFileResp) Reset() {
	*x = WasmOpenFileResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_js_bridge_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *WasmOpenFileResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WasmOpenFileResp) ProtoMessage() {}

func (x *WasmOpenFileResp) ProtoReflect() protoreflect.Message {
	mi := &file_js_bridge_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WasmOpenFileResp.ProtoReflect.Descriptor instead.
func (*WasmOpenFileResp) Descriptor() ([]byte, []int) {
	return file_js_bridge_proto_rawDescGZIP(), []int{1}
}

type WasmReadFileReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Failed bool `protobuf:"varint,1,opt,name=failed,proto3" json:"failed,omitempty"`
}

func (x *WasmReadFileReq) Reset() {
	*x = WasmReadFileReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_js_bridge_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *WasmReadFileReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WasmReadFileReq) ProtoMessage() {}

func (x *WasmReadFileReq) ProtoReflect() protoreflect.Message {
	mi := &file_js_bridge_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WasmReadFileReq.ProtoReflect.Descriptor instead.
func (*WasmReadFileReq) Descriptor() ([]byte, []int) {
	return file_js_bridge_proto_rawDescGZIP(), []int{2}
}

func (x *WasmReadFileReq) GetFailed() bool {
	if x != nil {
		return x.Failed
	}
	return false
}

type WasmReadFileResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *WasmReadFileResp) Reset() {
	*x = WasmReadFileResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_js_bridge_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *WasmReadFileResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WasmReadFileResp) ProtoMessage() {}

func (x *WasmReadFileResp) ProtoReflect() protoreflect.Message {
	mi := &file_js_bridge_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WasmReadFileResp.ProtoReflect.Descriptor instead.
func (*WasmReadFileResp) Descriptor() ([]byte, []int) {
	return file_js_bridge_proto_rawDescGZIP(), []int{3}
}

type WasmCloseFileReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *WasmCloseFileReq) Reset() {
	*x = WasmCloseFileReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_js_bridge_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *WasmCloseFileReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WasmCloseFileReq) ProtoMessage() {}

func (x *WasmCloseFileReq) ProtoReflect() protoreflect.Message {
	mi := &file_js_bridge_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WasmCloseFileReq.ProtoReflect.Descriptor instead.
func (*WasmCloseFileReq) Descriptor() ([]byte, []int) {
	return file_js_bridge_proto_rawDescGZIP(), []int{4}
}

type WasmCloseFileResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *WasmCloseFileResp) Reset() {
	*x = WasmCloseFileResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_js_bridge_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *WasmCloseFileResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WasmCloseFileResp) ProtoMessage() {}

func (x *WasmCloseFileResp) ProtoReflect() protoreflect.Message {
	mi := &file_js_bridge_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WasmCloseFileResp.ProtoReflect.Descriptor instead.
func (*WasmCloseFileResp) Descriptor() ([]byte, []int) {
	return file_js_bridge_proto_rawDescGZIP(), []int{5}
}

type JsSqliteOpenReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
}

func (x *JsSqliteOpenReq) Reset() {
	*x = JsSqliteOpenReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_js_bridge_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *JsSqliteOpenReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JsSqliteOpenReq) ProtoMessage() {}

func (x *JsSqliteOpenReq) ProtoReflect() protoreflect.Message {
	mi := &file_js_bridge_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JsSqliteOpenReq.ProtoReflect.Descriptor instead.
func (*JsSqliteOpenReq) Descriptor() ([]byte, []int) {
	return file_js_bridge_proto_rawDescGZIP(), []int{6}
}

func (x *JsSqliteOpenReq) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type JsSqliteOpenResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id int64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *JsSqliteOpenResp) Reset() {
	*x = JsSqliteOpenResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_js_bridge_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *JsSqliteOpenResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JsSqliteOpenResp) ProtoMessage() {}

func (x *JsSqliteOpenResp) ProtoReflect() protoreflect.Message {
	mi := &file_js_bridge_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JsSqliteOpenResp.ProtoReflect.Descriptor instead.
func (*JsSqliteOpenResp) Descriptor() ([]byte, []int) {
	return file_js_bridge_proto_rawDescGZIP(), []int{7}
}

func (x *JsSqliteOpenResp) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type JsSqliteCloseReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id int64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *JsSqliteCloseReq) Reset() {
	*x = JsSqliteCloseReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_js_bridge_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *JsSqliteCloseReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JsSqliteCloseReq) ProtoMessage() {}

func (x *JsSqliteCloseReq) ProtoReflect() protoreflect.Message {
	mi := &file_js_bridge_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JsSqliteCloseReq.ProtoReflect.Descriptor instead.
func (*JsSqliteCloseReq) Descriptor() ([]byte, []int) {
	return file_js_bridge_proto_rawDescGZIP(), []int{8}
}

func (x *JsSqliteCloseReq) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type JsSqliteCloseResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *JsSqliteCloseResp) Reset() {
	*x = JsSqliteCloseResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_js_bridge_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *JsSqliteCloseResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JsSqliteCloseResp) ProtoMessage() {}

func (x *JsSqliteCloseResp) ProtoReflect() protoreflect.Message {
	mi := &file_js_bridge_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JsSqliteCloseResp.ProtoReflect.Descriptor instead.
func (*JsSqliteCloseResp) Descriptor() ([]byte, []int) {
	return file_js_bridge_proto_rawDescGZIP(), []int{9}
}

type JsSqliteExecReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id   int64  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Sql  string `protobuf:"bytes,2,opt,name=sql,proto3" json:"sql,omitempty"`
	Args string `protobuf:"bytes,3,opt,name=args,proto3" json:"args,omitempty"` // json array
}

func (x *JsSqliteExecReq) Reset() {
	*x = JsSqliteExecReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_js_bridge_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *JsSqliteExecReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JsSqliteExecReq) ProtoMessage() {}

func (x *JsSqliteExecReq) ProtoReflect() protoreflect.Message {
	mi := &file_js_bridge_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JsSqliteExecReq.ProtoReflect.Descriptor instead.
func (*JsSqliteExecReq) Descriptor() ([]byte, []int) {
	return file_js_bridge_proto_rawDescGZIP(), []int{10}
}

func (x *JsSqliteExecReq) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *JsSqliteExecReq) GetSql() string {
	if x != nil {
		return x.Sql
	}
	return ""
}

func (x *JsSqliteExecReq) GetArgs() string {
	if x != nil {
		return x.Args
	}
	return ""
}

type JsSqliteExecResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Affected int64 `protobuf:"varint,1,opt,name=affected,proto3" json:"affected,omitempty"`
}

func (x *JsSqliteExecResp) Reset() {
	*x = JsSqliteExecResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_js_bridge_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *JsSqliteExecResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JsSqliteExecResp) ProtoMessage() {}

func (x *JsSqliteExecResp) ProtoReflect() protoreflect.Message {
	mi := &file_js_bridge_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JsSqliteExecResp.ProtoReflect.Descriptor instead.
func (*JsSqliteExecResp) Descriptor() ([]byte, []int) {
	return file_js_bridge_proto_rawDescGZIP(), []int{11}
}

func (x *JsSqliteExecResp) GetAffected() int64 {
	if x != nil {
		return x.Affected
	}
	return 0
}

type JsSqliteQueryReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id   int64  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Sql  string `protobuf:"bytes,2,opt,name=sql,proto3" json:"sql,omitempty"`
	Args string `protobuf:"bytes,3,opt,name=args,proto3" json:"args,omitempty"` // json array
}

func (x *JsSqliteQueryReq) Reset() {
	*x = JsSqliteQueryReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_js_bridge_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *JsSqliteQueryReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JsSqliteQueryReq) ProtoMessage() {}

func (x *JsSqliteQueryReq) ProtoReflect() protoreflect.Message {
	mi := &file_js_bridge_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JsSqliteQueryReq.ProtoReflect.Descriptor instead.
func (*JsSqliteQueryReq) Descriptor() ([]byte, []int) {
	return file_js_bridge_proto_rawDescGZIP(), []int{12}
}

func (x *JsSqliteQueryReq) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *JsSqliteQueryReq) GetSql() string {
	if x != nil {
		return x.Sql
	}
	return ""
}

func (x *JsSqliteQueryReq) GetArgs() string {
	if x != nil {
		return x.Args
	}
	return ""
}

type JsSqliteQueryResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Result string `protobuf:"bytes,1,opt,name=result,proto3" json:"result,omitempty"` // json array
}

func (x *JsSqliteQueryResp) Reset() {
	*x = JsSqliteQueryResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_js_bridge_proto_msgTypes[13]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *JsSqliteQueryResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JsSqliteQueryResp) ProtoMessage() {}

func (x *JsSqliteQueryResp) ProtoReflect() protoreflect.Message {
	mi := &file_js_bridge_proto_msgTypes[13]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JsSqliteQueryResp.ProtoReflect.Descriptor instead.
func (*JsSqliteQueryResp) Descriptor() ([]byte, []int) {
	return file_js_bridge_proto_rawDescGZIP(), []int{13}
}

func (x *JsSqliteQueryResp) GetResult() string {
	if x != nil {
		return x.Result
	}
	return ""
}

var File_js_bridge_proto protoreflect.FileDescriptor

var file_js_bridge_proto_rawDesc = []byte{
	0x0a, 0x0f, 0x6a, 0x73, 0x5f, 0x62, 0x72, 0x69, 0x64, 0x67, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x12, 0x09, 0x6f, 0x70, 0x65, 0x6e, 0x69, 0x6d, 0x2e, 0x6a, 0x73, 0x22, 0x2f, 0x0a, 0x0f,
	0x77, 0x61, 0x73, 0x6d, 0x4f, 0x70, 0x65, 0x6e, 0x46, 0x69, 0x6c, 0x65, 0x52, 0x65, 0x71, 0x12,
	0x1c, 0x0a, 0x09, 0x73, 0x71, 0x6c, 0x53, 0x74, 0x72, 0x69, 0x6e, 0x67, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x09, 0x73, 0x71, 0x6c, 0x53, 0x74, 0x72, 0x69, 0x6e, 0x67, 0x22, 0x12, 0x0a,
	0x10, 0x77, 0x61, 0x73, 0x6d, 0x4f, 0x70, 0x65, 0x6e, 0x46, 0x69, 0x6c, 0x65, 0x52, 0x65, 0x73,
	0x70, 0x22, 0x29, 0x0a, 0x0f, 0x77, 0x61, 0x73, 0x6d, 0x52, 0x65, 0x61, 0x64, 0x46, 0x69, 0x6c,
	0x65, 0x52, 0x65, 0x71, 0x12, 0x16, 0x0a, 0x06, 0x66, 0x61, 0x69, 0x6c, 0x65, 0x64, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x08, 0x52, 0x06, 0x66, 0x61, 0x69, 0x6c, 0x65, 0x64, 0x22, 0x12, 0x0a, 0x10,
	0x77, 0x61, 0x73, 0x6d, 0x52, 0x65, 0x61, 0x64, 0x46, 0x69, 0x6c, 0x65, 0x52, 0x65, 0x73, 0x70,
	0x22, 0x12, 0x0a, 0x10, 0x77, 0x61, 0x73, 0x6d, 0x43, 0x6c, 0x6f, 0x73, 0x65, 0x46, 0x69, 0x6c,
	0x65, 0x52, 0x65, 0x71, 0x22, 0x13, 0x0a, 0x11, 0x77, 0x61, 0x73, 0x6d, 0x43, 0x6c, 0x6f, 0x73,
	0x65, 0x46, 0x69, 0x6c, 0x65, 0x52, 0x65, 0x73, 0x70, 0x22, 0x25, 0x0a, 0x0f, 0x6a, 0x73, 0x53,
	0x71, 0x6c, 0x69, 0x74, 0x65, 0x4f, 0x70, 0x65, 0x6e, 0x52, 0x65, 0x71, 0x12, 0x12, 0x0a, 0x04,
	0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65,
	0x22, 0x22, 0x0a, 0x10, 0x6a, 0x73, 0x53, 0x71, 0x6c, 0x69, 0x74, 0x65, 0x4f, 0x70, 0x65, 0x6e,
	0x52, 0x65, 0x73, 0x70, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03,
	0x52, 0x02, 0x69, 0x64, 0x22, 0x22, 0x0a, 0x10, 0x6a, 0x73, 0x53, 0x71, 0x6c, 0x69, 0x74, 0x65,
	0x43, 0x6c, 0x6f, 0x73, 0x65, 0x52, 0x65, 0x71, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x03, 0x52, 0x02, 0x69, 0x64, 0x22, 0x13, 0x0a, 0x11, 0x6a, 0x73, 0x53, 0x71,
	0x6c, 0x69, 0x74, 0x65, 0x43, 0x6c, 0x6f, 0x73, 0x65, 0x52, 0x65, 0x73, 0x70, 0x22, 0x47, 0x0a,
	0x0f, 0x6a, 0x73, 0x53, 0x71, 0x6c, 0x69, 0x74, 0x65, 0x45, 0x78, 0x65, 0x63, 0x52, 0x65, 0x71,
	0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x02, 0x69, 0x64,
	0x12, 0x10, 0x0a, 0x03, 0x73, 0x71, 0x6c, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x73,
	0x71, 0x6c, 0x12, 0x12, 0x0a, 0x04, 0x61, 0x72, 0x67, 0x73, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x04, 0x61, 0x72, 0x67, 0x73, 0x22, 0x2e, 0x0a, 0x10, 0x6a, 0x73, 0x53, 0x71, 0x6c, 0x69,
	0x74, 0x65, 0x45, 0x78, 0x65, 0x63, 0x52, 0x65, 0x73, 0x70, 0x12, 0x1a, 0x0a, 0x08, 0x61, 0x66,
	0x66, 0x65, 0x63, 0x74, 0x65, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x08, 0x61, 0x66,
	0x66, 0x65, 0x63, 0x74, 0x65, 0x64, 0x22, 0x48, 0x0a, 0x10, 0x6a, 0x73, 0x53, 0x71, 0x6c, 0x69,
	0x74, 0x65, 0x51, 0x75, 0x65, 0x72, 0x79, 0x52, 0x65, 0x71, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x02, 0x69, 0x64, 0x12, 0x10, 0x0a, 0x03, 0x73, 0x71,
	0x6c, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x73, 0x71, 0x6c, 0x12, 0x12, 0x0a, 0x04,
	0x61, 0x72, 0x67, 0x73, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x61, 0x72, 0x67, 0x73,
	0x22, 0x2b, 0x0a, 0x11, 0x6a, 0x73, 0x53, 0x71, 0x6c, 0x69, 0x74, 0x65, 0x51, 0x75, 0x65, 0x72,
	0x79, 0x52, 0x65, 0x73, 0x70, 0x12, 0x16, 0x0a, 0x06, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x42, 0x2f, 0x5a,
	0x2d, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x6f, 0x70, 0x65, 0x6e,
	0x69, 0x6d, 0x73, 0x64, 0x6b, 0x2f, 0x6f, 0x70, 0x65, 0x6e, 0x69, 0x6d, 0x2d, 0x73, 0x64, 0x6b,
	0x2d, 0x63, 0x6f, 0x72, 0x65, 0x2f, 0x76, 0x33, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x06,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_js_bridge_proto_rawDescOnce sync.Once
	file_js_bridge_proto_rawDescData = file_js_bridge_proto_rawDesc
)

func file_js_bridge_proto_rawDescGZIP() []byte {
	file_js_bridge_proto_rawDescOnce.Do(func() {
		file_js_bridge_proto_rawDescData = protoimpl.X.CompressGZIP(file_js_bridge_proto_rawDescData)
	})
	return file_js_bridge_proto_rawDescData
}

var file_js_bridge_proto_msgTypes = make([]protoimpl.MessageInfo, 14)
var file_js_bridge_proto_goTypes = []interface{}{
	(*WasmOpenFileReq)(nil),   // 0: openim.js.wasmOpenFileReq
	(*WasmOpenFileResp)(nil),  // 1: openim.js.wasmOpenFileResp
	(*WasmReadFileReq)(nil),   // 2: openim.js.wasmReadFileReq
	(*WasmReadFileResp)(nil),  // 3: openim.js.wasmReadFileResp
	(*WasmCloseFileReq)(nil),  // 4: openim.js.wasmCloseFileReq
	(*WasmCloseFileResp)(nil), // 5: openim.js.wasmCloseFileResp
	(*JsSqliteOpenReq)(nil),   // 6: openim.js.jsSqliteOpenReq
	(*JsSqliteOpenResp)(nil),  // 7: openim.js.jsSqliteOpenResp
	(*JsSqliteCloseReq)(nil),  // 8: openim.js.jsSqliteCloseReq
	(*JsSqliteCloseResp)(nil), // 9: openim.js.jsSqliteCloseResp
	(*JsSqliteExecReq)(nil),   // 10: openim.js.jsSqliteExecReq
	(*JsSqliteExecResp)(nil),  // 11: openim.js.jsSqliteExecResp
	(*JsSqliteQueryReq)(nil),  // 12: openim.js.jsSqliteQueryReq
	(*JsSqliteQueryResp)(nil), // 13: openim.js.jsSqliteQueryResp
}
var file_js_bridge_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_js_bridge_proto_init() }
func file_js_bridge_proto_init() {
	if File_js_bridge_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_js_bridge_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*WasmOpenFileReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_js_bridge_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*WasmOpenFileResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_js_bridge_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*WasmReadFileReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_js_bridge_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*WasmReadFileResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_js_bridge_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*WasmCloseFileReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_js_bridge_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*WasmCloseFileResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_js_bridge_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*JsSqliteOpenReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_js_bridge_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*JsSqliteOpenResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_js_bridge_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*JsSqliteCloseReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_js_bridge_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*JsSqliteCloseResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_js_bridge_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*JsSqliteExecReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_js_bridge_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*JsSqliteExecResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_js_bridge_proto_msgTypes[12].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*JsSqliteQueryReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_js_bridge_proto_msgTypes[13].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*JsSqliteQueryResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_js_bridge_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   14,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_js_bridge_proto_goTypes,
		DependencyIndexes: file_js_bridge_proto_depIdxs,
		MessageInfos:      file_js_bridge_proto_msgTypes,
	}.Build()
	File_js_bridge_proto = out.File
	file_js_bridge_proto_rawDesc = nil
	file_js_bridge_proto_goTypes = nil
	file_js_bridge_proto_depIdxs = nil
}
