// source: common.proto
/**
 * @fileoverview
 * @enhanceable
 * @suppress {missingRequire} reports error on implicit type usages.
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!
/* eslint-disable */
// @ts-nocheck

var jspb = require('google-protobuf');
var goog = jspb;
var global =
    (typeof globalThis !== 'undefined' && globalThis) ||
    (typeof window !== 'undefined' && window) ||
    (typeof global !== 'undefined' && global) ||
    (typeof self !== 'undefined' && self) ||
    (function () { return this; }).call(null) ||
    Function('return this')();

goog.exportSymbol('proto.openim.sdk.common.AppFramework', null, global);
goog.exportSymbol('proto.openim.sdk.common.ApprovalStatus', null, global);
goog.exportSymbol('proto.openim.sdk.common.ContentType', null, global);
goog.exportSymbol('proto.openim.sdk.common.MsgFrom', null, global);
goog.exportSymbol('proto.openim.sdk.common.MsgStatus', null, global);
goog.exportSymbol('proto.openim.sdk.common.OfflinePushInfo', null, global);
goog.exportSymbol('proto.openim.sdk.common.Platform', null, global);
goog.exportSymbol('proto.openim.sdk.common.RequestPagination', null, global);
goog.exportSymbol('proto.openim.sdk.common.SessionType', null, global);
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.openim.sdk.common.OfflinePushInfo = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.openim.sdk.common.OfflinePushInfo, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.openim.sdk.common.OfflinePushInfo.displayName = 'proto.openim.sdk.common.OfflinePushInfo';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.openim.sdk.common.RequestPagination = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.openim.sdk.common.RequestPagination, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.openim.sdk.common.RequestPagination.displayName = 'proto.openim.sdk.common.RequestPagination';
}



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.openim.sdk.common.OfflinePushInfo.prototype.toObject = function(opt_includeInstance) {
  return proto.openim.sdk.common.OfflinePushInfo.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.openim.sdk.common.OfflinePushInfo} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.openim.sdk.common.OfflinePushInfo.toObject = function(includeInstance, msg) {
  var f, obj = {
title: jspb.Message.getFieldWithDefault(msg, 1, ""),
desc: jspb.Message.getFieldWithDefault(msg, 2, ""),
ex: jspb.Message.getFieldWithDefault(msg, 3, ""),
iospushsound: jspb.Message.getFieldWithDefault(msg, 4, ""),
iosbadgecount: jspb.Message.getBooleanFieldWithDefault(msg, 5, false),
signalinfo: jspb.Message.getFieldWithDefault(msg, 6, "")
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.openim.sdk.common.OfflinePushInfo}
 */
proto.openim.sdk.common.OfflinePushInfo.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.openim.sdk.common.OfflinePushInfo;
  return proto.openim.sdk.common.OfflinePushInfo.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.openim.sdk.common.OfflinePushInfo} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.openim.sdk.common.OfflinePushInfo}
 */
proto.openim.sdk.common.OfflinePushInfo.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setTitle(value);
      break;
    case 2:
      var value = /** @type {string} */ (reader.readString());
      msg.setDesc(value);
      break;
    case 3:
      var value = /** @type {string} */ (reader.readString());
      msg.setEx(value);
      break;
    case 4:
      var value = /** @type {string} */ (reader.readString());
      msg.setIospushsound(value);
      break;
    case 5:
      var value = /** @type {boolean} */ (reader.readBool());
      msg.setIosbadgecount(value);
      break;
    case 6:
      var value = /** @type {string} */ (reader.readString());
      msg.setSignalinfo(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.openim.sdk.common.OfflinePushInfo.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.openim.sdk.common.OfflinePushInfo.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.openim.sdk.common.OfflinePushInfo} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.openim.sdk.common.OfflinePushInfo.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getTitle();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
  f = message.getDesc();
  if (f.length > 0) {
    writer.writeString(
      2,
      f
    );
  }
  f = message.getEx();
  if (f.length > 0) {
    writer.writeString(
      3,
      f
    );
  }
  f = message.getIospushsound();
  if (f.length > 0) {
    writer.writeString(
      4,
      f
    );
  }
  f = message.getIosbadgecount();
  if (f) {
    writer.writeBool(
      5,
      f
    );
  }
  f = message.getSignalinfo();
  if (f.length > 0) {
    writer.writeString(
      6,
      f
    );
  }
};


/**
 * optional string title = 1;
 * @return {string}
 */
proto.openim.sdk.common.OfflinePushInfo.prototype.getTitle = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/**
 * @param {string} value
 * @return {!proto.openim.sdk.common.OfflinePushInfo} returns this
 */
proto.openim.sdk.common.OfflinePushInfo.prototype.setTitle = function(value) {
  return jspb.Message.setProto3StringField(this, 1, value);
};


/**
 * optional string desc = 2;
 * @return {string}
 */
proto.openim.sdk.common.OfflinePushInfo.prototype.getDesc = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 2, ""));
};


/**
 * @param {string} value
 * @return {!proto.openim.sdk.common.OfflinePushInfo} returns this
 */
proto.openim.sdk.common.OfflinePushInfo.prototype.setDesc = function(value) {
  return jspb.Message.setProto3StringField(this, 2, value);
};


/**
 * optional string ex = 3;
 * @return {string}
 */
proto.openim.sdk.common.OfflinePushInfo.prototype.getEx = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 3, ""));
};


/**
 * @param {string} value
 * @return {!proto.openim.sdk.common.OfflinePushInfo} returns this
 */
proto.openim.sdk.common.OfflinePushInfo.prototype.setEx = function(value) {
  return jspb.Message.setProto3StringField(this, 3, value);
};


/**
 * optional string iOSPushSound = 4;
 * @return {string}
 */
proto.openim.sdk.common.OfflinePushInfo.prototype.getIospushsound = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 4, ""));
};


/**
 * @param {string} value
 * @return {!proto.openim.sdk.common.OfflinePushInfo} returns this
 */
proto.openim.sdk.common.OfflinePushInfo.prototype.setIospushsound = function(value) {
  return jspb.Message.setProto3StringField(this, 4, value);
};


/**
 * optional bool iOSBadgeCount = 5;
 * @return {boolean}
 */
proto.openim.sdk.common.OfflinePushInfo.prototype.getIosbadgecount = function() {
  return /** @type {boolean} */ (jspb.Message.getBooleanFieldWithDefault(this, 5, false));
};


/**
 * @param {boolean} value
 * @return {!proto.openim.sdk.common.OfflinePushInfo} returns this
 */
proto.openim.sdk.common.OfflinePushInfo.prototype.setIosbadgecount = function(value) {
  return jspb.Message.setProto3BooleanField(this, 5, value);
};


/**
 * optional string signalInfo = 6;
 * @return {string}
 */
proto.openim.sdk.common.OfflinePushInfo.prototype.getSignalinfo = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 6, ""));
};


/**
 * @param {string} value
 * @return {!proto.openim.sdk.common.OfflinePushInfo} returns this
 */
proto.openim.sdk.common.OfflinePushInfo.prototype.setSignalinfo = function(value) {
  return jspb.Message.setProto3StringField(this, 6, value);
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.openim.sdk.common.RequestPagination.prototype.toObject = function(opt_includeInstance) {
  return proto.openim.sdk.common.RequestPagination.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.openim.sdk.common.RequestPagination} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.openim.sdk.common.RequestPagination.toObject = function(includeInstance, msg) {
  var f, obj = {
pagenumber: jspb.Message.getFieldWithDefault(msg, 1, 0),
shownumber: jspb.Message.getFieldWithDefault(msg, 2, 0)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.openim.sdk.common.RequestPagination}
 */
proto.openim.sdk.common.RequestPagination.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.openim.sdk.common.RequestPagination;
  return proto.openim.sdk.common.RequestPagination.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.openim.sdk.common.RequestPagination} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.openim.sdk.common.RequestPagination}
 */
proto.openim.sdk.common.RequestPagination.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {number} */ (reader.readInt32());
      msg.setPagenumber(value);
      break;
    case 2:
      var value = /** @type {number} */ (reader.readInt32());
      msg.setShownumber(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.openim.sdk.common.RequestPagination.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.openim.sdk.common.RequestPagination.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.openim.sdk.common.RequestPagination} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.openim.sdk.common.RequestPagination.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getPagenumber();
  if (f !== 0) {
    writer.writeInt32(
      1,
      f
    );
  }
  f = message.getShownumber();
  if (f !== 0) {
    writer.writeInt32(
      2,
      f
    );
  }
};


/**
 * optional int32 pageNumber = 1;
 * @return {number}
 */
proto.openim.sdk.common.RequestPagination.prototype.getPagenumber = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 1, 0));
};


/**
 * @param {number} value
 * @return {!proto.openim.sdk.common.RequestPagination} returns this
 */
proto.openim.sdk.common.RequestPagination.prototype.setPagenumber = function(value) {
  return jspb.Message.setProto3IntField(this, 1, value);
};


/**
 * optional int32 showNumber = 2;
 * @return {number}
 */
proto.openim.sdk.common.RequestPagination.prototype.getShownumber = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 2, 0));
};


/**
 * @param {number} value
 * @return {!proto.openim.sdk.common.RequestPagination} returns this
 */
proto.openim.sdk.common.RequestPagination.prototype.setShownumber = function(value) {
  return jspb.Message.setProto3IntField(this, 2, value);
};


/**
 * @enum {number}
 */
proto.openim.sdk.common.SessionType = {
  SESSIONTYPE_: 0,
  SINGLECHATTYPE: 1,
  WRITEGROUPCHATTYPE: 2,
  READGROUPCHATTYPE: 3,
  NOTIFICATIONCHATTYPE: 4
};

/**
 * @enum {number}
 */
proto.openim.sdk.common.MsgFrom = {
  MSGFROM_: 0,
  USERMSGTYPE: 100,
  SYSMSGTYPE: 200
};

/**
 * @enum {number}
 */
proto.openim.sdk.common.Platform = {
  PLATFORM_: 0,
  IOS: 1,
  ANDROID: 2,
  WINDOWS: 3,
  MACOS: 4,
  WEB: 5,
  MINIWEB: 6,
  LINUX: 7,
  ANDROIDPAD: 8,
  IPAD: 9,
  ADMIN: 10,
  HARMONYOS: 11
};

/**
 * @enum {number}
 */
proto.openim.sdk.common.AppFramework = {
  APPFRAMEWORK_: 0,
  NATIVE: 1,
  FLUTTER: 2,
  REACTNATIVE: 3,
  ELECTRON: 4,
  UNITY: 5,
  UNREALENGINE: 6,
  QT: 7,
  DOTNET: 8,
  DOTNETMAUI: 9,
  AVALONIA: 10,
  CORDOVA: 11,
  UNIAPP: 12
};

/**
 * @enum {number}
 */
proto.openim.sdk.common.MsgStatus = {
  MSGSTATUS_: 0,
  SENDING: 1,
  SENDSUCCESS: 2,
  SENDFAILED: 3,
  HASDELETED: 4,
  FILTERED: 5
};

/**
 * @enum {number}
 */
proto.openim.sdk.common.ContentType = {
  CONTENTTYPE_: 0,
  TEXT: 101,
  PICTURE: 102,
  SOUND: 103,
  VIDEO: 104,
  FILE: 105,
  ATTEXT: 106,
  MERGE: 107,
  CARD: 108,
  LOCATION: 109,
  CUSTOM: 110,
  TYPING: 113,
  QUOTE: 114,
  FACE: 115,
  ADVANCEDTEXT: 117,
  CUSTOMMSGNOTTRIGGERCONVERSATION: 119,
  CUSTOMMSGONLINEONLY: 120,
  FRIENDAPPLICATIONAPPROVEDNOTIFICATION: 1201,
  FRIENDAPPLICATIONREJECTEDNOTIFICATION: 1202,
  FRIENDAPPLICATIONNOTIFICATION: 1203,
  FRIENDADDEDNOTIFICATION: 1204,
  FRIENDDELETEDNOTIFICATION: 1205,
  FRIENDREMARKSETNOTIFICATION: 1206,
  BLACKADDEDNOTIFICATION: 1207,
  BLACKDELETEDNOTIFICATION: 1208,
  FRIENDINFOUPDATEDNOTIFICATION: 1209,
  FRIENDSINFOUPDATENOTIFICATION: 1210,
  CONVERSATIONCHANGENOTIFICATION: 1300,
  USERINFOUPDATEDNOTIFICATION: 1303,
  USERSTATUSCHANGENOTIFICATION: 1304,
  USERCOMMANDADDNOTIFICATION: 1305,
  USERCOMMANDDELETENOTIFICATION: 1306,
  USERCOMMANDUPDATENOTIFICATION: 1307,
  GROUPCREATEDNOTIFICATION: 1501,
  GROUPINFOSETNOTIFICATION: 1502,
  JOINGROUPAPPLICATIONNOTIFICATION: 1503,
  MEMBERQUITNOTIFICATION: 1504,
  GROUPAPPLICATIONACCEPTEDNOTIFICATION: 1505,
  GROUPAPPLICATIONREJECTEDNOTIFICATION: 1506,
  GROUPOWNERTRANSFERREDNOTIFICATION: 1507,
  MEMBERKICKEDNOTIFICATION: 1508,
  MEMBERINVITEDNOTIFICATION: 1509,
  MEMBERENTERNOTIFICATION: 1510,
  GROUPDISMISSEDNOTIFICATION: 1511,
  GROUPMEMBERMUTEDNOTIFICATION: 1512,
  GROUPMEMBERCANCELMUTEDNOTIFICATION: 1513,
  GROUPMUTEDNOTIFICATION: 1514,
  GROUPCANCELMUTEDNOTIFICATION: 1515,
  GROUPMEMBERINFOSETNOTIFICATION: 1516,
  GROUPMEMBERSETTOADMINNOTIFICATION: 1517,
  GROUPMEMBERSETTOORDINARYUSERNOTIFICATION: 1518,
  GROUPINFOSETANNOUNCEMENTNOTIFICATION: 1519,
  GROUPINFOSETNAMENOTIFICATION: 1520,
  CONVERSATIONPRIVATECHATNOTIFICATION: 1701,
  CLEARCONVERSATIONNOTIFICATION: 1703,
  BUSINESSNOTIFICATION: 2001,
  REVOKENOTIFICATION: 2101,
  DELETEMSGSNOTIFICATION: 2102,
  HASREADRECEIPT: 2200
};

/**
 * @enum {number}
 */
proto.openim.sdk.common.ApprovalStatus = {
  DEFAULT: 0,
  APPROVED: 1,
  REJECTED: -1
};

goog.object.extend(exports, proto.openim.sdk.common);
